# Generated by Django 5.2.5 on 2025-08-11 05:33

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_gallery',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='photo_gallery',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='photo_gallery',
            name='title',
            field=models.CharField(default='Photo image', max_length=32),
        ),
    ]
