# Generated by Django 5.2.5 on 2025-08-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery_app', '0004_alter_photo_gallery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
    ]
