# Generated by Django 5.2.5 on 2025-08-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery_app', '0005_remove_user_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_gallery',
            name='user',
        ),
    ]
